### ISSUE TITLE
Add 2019 dates and promo video

### ISSUE THREAD

**Issue by BigBlueHat** [RESTFest/restfest.github.io#2]
https://vimeo.com/314900676

The time has come! 😁 

We can link the dates to the sub-sites once those are ready to go.

Cool?

**Comment by mamund** [comment]
very cool. i'll sked a tweet for this week and start sharing!

we need that new landing page so people can start signing up<g>!

**Comment by BigBlueHat** [comment]
k. Dates are up! https://github.com/RESTFest/restfest.github.io/commit/1bc1fe648af7e091521474a80d8bb210b80ed46a

@oestrich now we need to tackle the sub-sites!
